#!/bin/sh


mount -t proc comment proc/

mount -t sysfs comment sys/

ARG=$1

if [ "$ARG" -eq 3 ]
then

	for i in /etc/init.d/S??*
	do	
		$i start
	done
fi	
	
if [ "$ARG" -eq 5 ]
then

	for i in /etc/init.d/K??*
	do	
		$i stop
	done
fi	


